# env vars
export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

export ZLS_COLORS_CUSTOM='di=34;40:ln=35;40:so=32;40:pi=33;40:ex=31;40:bd=34;46:cd=34;43:su=0;41:sg=0;46:tw=0;42:ow=0;43:'

# 256 color mode
export TERM=xterm-256color

# cocoapods
export LC_ALL="en_US.UTF-8"

##################
### PATH Setup ###
##################

export PATH=""
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/.bin"

# ~/Developer default root for any project
export DEVELOPER="/Users/hamsternik/Developer"
export PATH=$PATH:$DEVELOPER

# Zsh git prompt
export GITSTATUS=$DOTFILES/.zsh/zsh-git-prompt/src
export PATH=$PATH:$GITSTATUS/.bin

# Xcode default path to the SoucreKit-LSP binary (Swift)
export SOURCEKIT_TOOLCHAIN_PATH=`xcrun --find sourcekit-lsp`
export PATH=$PATH:$SOURCEKIT_TOOLCHAIN_PATH

# Ruby | rbenv
export RBENV_SHIMS="$HOME/.rbenv/shims"
export PATH=$PATH:$RBENV_SHIMS
export RBENV_SHELL=zsh

export RBENV_BIN="$HOME/.rbenv/bin"
export PATH=$PATH:$RBENV_BIN

# Fastlane
export FASTLANE="$HOME/.fastlane/bin"
export PATH=$PATH:$FASTLANE

# Java Lang
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
export PATH=${PATH}:${JAVA_HOME}/bin

# Android
export ANDROID_HOME=${HOME}/Library/Android/sdk
export PATH=$PATH:${ANDROID_HOME}/tools
export PATH=$PATH:${ANDROID_HOME}/platform-tools

# Go Lang
export GOPATH=$HOME/Developer/go
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

# OpenSSL
# before make ln -s /path/to/openssl-by-brew /usr/local/openssl
# as ex.: ln -s /usr/local/Cellar/openssl/1.0.2j/bin/openssl /usr/local/openssl
export OPENSSL_BREW=/usr/local/Cellar/openssl/1.0.2j/bin
export PATH=$OPENSSL_BREW:$PATH

# NVM
export NVM_AUTO_USE=true
